// File generated by FlutterFire CLI.
// NOTE: This project uses Android flavor-specific `google-services.json`
// files to initialize Firebase on Android. To avoid accidental use of
// the generated options on mobile platforms we expose the `web` options
// here and make `currentPlatform` explicitly Web-only. If you need to
// regenerate Web options run the FlutterFire CLI and replace the
// `web` constant below.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  /// Returns web-only FirebaseOptions.
  ///
  /// On mobile platforms (Android/iOS) this project initializes Firebase
  /// using the native `google-services.json` / `GoogleService-Info.plist`
  /// files per flavor via `await Firebase.initializeApp()` in each flavor
  /// entrypoint (e.g. `lib/main_customer.dart`). Do not use
  /// `DefaultFirebaseOptions.currentPlatform` on mobile flavors.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError(
      'DefaultFirebaseOptions.currentPlatform is intended for Web only. '
      'For Android/iOS flavors initialize Firebase with the native '
      'google-services.json/GoogleService-Info.plist by calling '
      '`await Firebase.initializeApp()` in each flavor main. To regenerate '
      'Web options run the FlutterFire CLI and replace the `web` section.'
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNySUUITwm6U9cpm757HcFY7jn3I5GtEA',
    appId: '1:612832799916:web:034cc60f6eeffb7c3d0309',
    messagingSenderId: '612832799916',
    projectId: 'barber-pro-20d4b',
    authDomain: 'barber-pro-20d4b.firebaseapp.com',
    storageBucket: 'barber-pro-20d4b.firebasestorage.app',
    measurementId: 'G-W6KG07991R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKENmeWJUcH0FmwxjcHt5as_pZzjHq7qc',
    appId: '1:612832799916:android:7f85f8230c76fd163d0309',
    messagingSenderId: '612832799916',
    projectId: 'barber-pro-20d4b',
    storageBucket: 'barber-pro-20d4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkxToQPmF1AhM9mU0u-L08DYCQn7wbonM',
    appId: '1:612832799916:ios:e15082115f99d6f73d0309',
    messagingSenderId: '612832799916',
    projectId: 'barber-pro-20d4b',
    storageBucket: 'barber-pro-20d4b.firebasestorage.app',
    androidClientId: '612832799916-ebupr20pp9uirq25eu7qnl2vrrdl9gnh.apps.googleusercontent.com',
    iosClientId: '612832799916-srjjs1dpv8ch2miiskn21oa9ases7gpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.newbarberproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkxToQPmF1AhM9mU0u-L08DYCQn7wbonM',
    appId: '1:612832799916:ios:e15082115f99d6f73d0309',
    messagingSenderId: '612832799916',
    projectId: 'barber-pro-20d4b',
    storageBucket: 'barber-pro-20d4b.firebasestorage.app',
    androidClientId: '612832799916-ebupr20pp9uirq25eu7qnl2vrrdl9gnh.apps.googleusercontent.com',
    iosClientId: '612832799916-srjjs1dpv8ch2miiskn21oa9ases7gpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.newbarberproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNySUUITwm6U9cpm757HcFY7jn3I5GtEA',
    appId: '1:612832799916:web:e45364b7c2d984f23d0309',
    messagingSenderId: '612832799916',
    projectId: 'barber-pro-20d4b',
    authDomain: 'barber-pro-20d4b.firebaseapp.com',
    storageBucket: 'barber-pro-20d4b.firebasestorage.app',
    measurementId: 'G-K8ZZQ6Y9MT',
  );

}

// Import this in main.dart like: 
// import 'firebase_options.dart';
// Then use: options: DefaultFirebaseOptions.currentPlatform